### ISSUE TITLE
go tests are failing

### ISSUE THREAD

**Issue by ghost** [TileDB-Inc/TileDB-Go#219] opened 2022-05-03 20:28 UTC
Hi, I am using tiledb core 2.3.4 and it looks like `go get ...` fetched tiledb-go version `v0.15.1`. When running `go test github.com/TileDB-Inc/TileDB-Go` I get the following:

```
aws_access_key_id: 
aws_external_id: 
aws_load_frequency: 
aws_role_arn: 
aws_secret_access_key: 
aws_session_name: 
aws_session_token: 
ca_file: 
ca_path: 
connect_max_tries: 5
connect_scale_factor: 25
connect_timeout_ms: 10800
endpoint_override: 
logging_level: Off
max_parallel_ops: 64
multipart_part_size: 5242880
proxy_host: 
proxy_password: 
proxy_port: 0
proxy_scheme: http
proxy_username: 
region: us-east-1
request_timeout_ms: 3000
requester_pays: false
scheme: https
skip_init: false
sse: 
sse_kms_key_id: 
use_multipart_upload: true
use_virtual_addressing: true
verify_ssl: true
--- FAIL: TestFragmentInfo (0.02s)
    fragment_info_test.go:23: 
        	Error Trace:	fragment_info_test.go:23
        	Error:      	Not equal: 
        	            	expected: 0x1055
        	            	actual  : 0x8a5
        	Test:       	TestFragmentInfo
--- FAIL: TestFragmentInfoEncryption (0.03s)
    fragment_info_test.go:43: 
        	Error Trace:	fragment_info_test.go:43
        	Error:      	Not equal: 
        	            	expected: 0x1cef
        	            	actual  : 0x8a5
        	Test:       	TestFragmentInfoEncryption
FAIL
FAIL	github.com/TileDB-Inc/TileDB-Go	0.592s
FAIL

```

**Comment by NullHypothesis** [comment] 2024-05-11 23:06
Closing this because the issue is old and tests should pass just fine now.

**Closed by NullHypothesis** 2024-05-11 23:06 UTC
